on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: run action
        uses: ./ # Uses an action in the root directory
        with:
          action: build
