name: test

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths:
      - "action.yml"
      - "Dockerfile"
      - "src/**"

concurrency:
  group:  ${{ github.workflow }}-${{github.event_name}}-${{ github.ref }}
  cancel-in-progress: true      

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: update action.yml to build locally
        run: |
          sed -i 's/.*image\:.*/  image\: \"Dockerfile\"/' action.yml
          cat action.yml      

      - name: build
        uses: ./ # Uses an action in the root directory
        with:
          action: build

      - name: export
        uses: ./ # Uses an action in the root directory
        with:
          export: png
          output: images

      - name: build with binary
        uses: ./ # Uses an action in the root directory
        with:
          output: dist-binary
          use-dot-bin: 'true'

      - name: codegen react
        uses: ./ # Uses an action in the root directory
        with:
          action: codegen

      - name: codegen mmd
        uses: ./ # Uses an action in the root directory
        with:
          codegen: mmd
          output: mmd
          
      - name: upload images
        uses: actions/upload-artifact@v4
        with:
          path: images/
